apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rag-test1-gitops
  description: This is GitOps manifest for rag-test1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=rag-test1
    janus-idp.io/tekton: rag-test1 
    backstage.io/kubernetes-id: rag-test1 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:default/tpetkos 
  lifecycle: experimental
  dependsOn:
    - component:rag-test1  
